version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev

    depends_on:
      - db
    networks:
      - mynetwork  # 네트워크 설정을 추가한 부분
  db:
    image : postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=do_it_django_db_user
      - POSTGRES_PASSWORD=do_it_django_db_password
      - POSTGRES_DB=do_it_django_dev
    networks:
      - mynetwork  # 네트워크 설정을 추가한 부분
networks:
  mynetwork:  # 네트워크 설정을 추가한 부분
    external: true
volumes:
  postgres_data:
